#!/bin/sh
checkpoint=192.168.1.254
pidfile=/var/run/fakeupsd.pid
tolerance=4200

ping -c 1 ${checkpoint} > /dev/null && touch ${pidfile}
last=`stat -f %m ${pidfile}`
now=`date +%s`
expr ${now} - ${last} '>=' ${tolerance} > /dev/null && logger "router down" && shutdown -h now "router down"
